"""Add from_ and to fields to Timetable

Revision ID: 40bef4a8e664
Revises: e50732a1e390
Create Date: 2024-09-30 09:12:08.451665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40bef4a8e664'
down_revision: Union[str, None] = 'e50732a1e390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('from_', sa.DateTime(), nullable=True))
    op.add_column('timetables', sa.Column('to', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetables', 'to')
    op.drop_column('timetables', 'from_')
    # ### end Alembic commands ###
